let known=new Set(),firstLoad=true,soundReady=false,settings=null;
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0)/100);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const time=v=>new Intl.DateTimeFormat('fr-FR',{timeZone:'America/Martinique',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
async function api(url,opt={}){const r=await fetch(url,{cache:'no-store',headers:{'content-type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Erreur serveur');return d}
async function loadSettings(){settings=await api('/api/admin/settings');document.querySelector('#orderingText').innerHTML=settings.can_order?'<span style="color:#54d98c">● COMMANDES OUVERTES</span>':'<span style="color:#ff7777">● COMMANDES FERMÉES</span>';document.querySelector('#waitText').textContent=`17h30 → commandes 22h00 → fermeture 22h20`;const b=document.querySelector('#closureBtn');b.textContent=settings.ordering_enabled?'FERMETURE EXCEPTIONNELLE':'RÉOUVRIR LES COMMANDES';b.className='close-btn '+(settings.ordering_enabled?'open':'closed');document.querySelector('#printerState').innerHTML=settings.printer_server_direct_configured?'<span class="print-ok">✓ File Epson configurée côté serveur</span>':'<span class="print-wait">⚠ Secret EPSON_PRINTER_ID à configurer avant impression réelle</span>'}
function orderCode(id){const A='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let n=BigInt(String(id))%BigInt(A.length**4),o='';for(let i=0;i<4;i++){o=A[Number(n%BigInt(A.length))]+o;n/=BigInt(A.length)}return o}
function beep(){if(!soundReady)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C();[0,.18,.36,.54].forEach((delay,i)=>{const o=c.createOscillator(),g=c.createGain();o.type='square';o.frequency.value=i%2?880:660;g.gain.setValueAtTime(.22,c.currentTime+delay);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+delay+.13);o.connect(g).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+.14)});navigator.vibrate?.([300,100,300,100,500])}catch{}}
function notifyNew(){document.querySelector('#orderAlert').classList.add('show');setTimeout(()=>document.querySelector('#orderAlert').classList.remove('show'),6000);beep();if(Notification.permission==='granted')new Notification('Planet Pizza — Nouvelle commande',{body:'Une nouvelle commande payée vient d’arriver.',tag:'planet-pizza-order'})}
async function loadOrders(){try{const d=await api('/api/admin/orders?limit=250');const active=(d.orders||[]).filter(o=>['confirmed','preparing','ready'].includes(o.status)&&o.payment_status==='paid');const ids=new Set(active.map(o=>String(o.id)));if(!firstLoad){const fresh=active.filter(o=>!known.has(String(o.id)));if(fresh.length)notifyNew()}known=ids;firstLoad=false;renderOrders(active)}catch(e){document.querySelector('#orders').innerHTML=`<div class="info">${esc(e.message)}</div>`}}
function renderOrders(list){const root=document.querySelector('#orders');root.innerHTML=list.length?list.map(o=>{const items=(o.items||[]).map(i=>{const x=i.options||{};const meta=[x.size_label,x.dough_type==='fine'?'PÂTE FINE':x.dough_type==='epaisse'?'PÂTE ÉPAISSE':'',x.promotion_label].filter(Boolean).join(' · ');return `<div class="line ${x.promotion?'promo':''}"><strong>${i.quantity} × ${esc(i.product_name)}</strong>${meta?`<div class="muted">${esc(meta)}</div>`:''}</div>`}).join('');const isReady=o.status==='ready';return `<article class="order ${isReady?'ready':''}"><div class="order-number">${orderCode(o.id)}</div><div class="order-time">${time(o.created_at)}</div><div class="muted">HEURE DE COMMANDE</div>${o.estimated_ready_at?`<div class="ready-time">Retrait estimé ${time(o.estimated_ready_at)}</div>`:''}<h3>${esc(o.customer_name)} · ${euro(o.total_cents)}</h3><div class="items">${items}</div><div class="${o.printed_at?'print-ok':'print-wait'}">${o.printed_at?'✓ Ticket imprimé':'⏳ Ticket en attente Epson'}</div>${o.notes?`<p>📝 ${esc(o.notes)}</p>`:''}<button class="kbtn ${isReady?'done':'ready'}" data-id="${o.id}" data-next="${isReady?'completed':'ready'}">${isReady?'COMMANDE REMISE':'COMMANDE PRÊTE'}</button></article>`}).join(''):'<div class="info">Aucune commande active.</div>';document.querySelectorAll('[data-next]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/admin/orders',{method:'PATCH',body:JSON.stringify({id:Number(b.dataset.id),status:b.dataset.next})});await loadOrders()}catch(e){alert(e.message);b.disabled=false}})}
async function loadStocks(){const d=await api('/api/admin/stocks');document.querySelector('#stocks').innerHTML=(d.stocks||[]).map(s=>`<div class="stock ${s.low?'low':''}"><h3>${s.dough_type==='fine'?'Pâte fine':'Pâte épaisse'} — ${s.size_code}</h3><label>Quantité de pâtons<input type="number" min="0" step="1" value="${s.quantity}" data-qty="${s.id}"></label><label>Seuil alerte<input type="number" min="0" step="1" value="${s.low_threshold}" data-low="${s.id}"></label><button data-save="${s.id}">${s.configured?'Mettre à jour':'Activer ce stock'}</button>${!s.configured?'<p class="muted">Non configuré : ne bloque pas encore les commandes.</p>':''}</div>`).join('');document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const id=Number(b.dataset.save),quantity=Number(document.querySelector(`[data-qty="${id}"]`).value),low_threshold=Number(document.querySelector(`[data-low="${id}"]`).value);await api('/api/admin/stocks',{method:'PATCH',body:JSON.stringify({id,quantity,low_threshold})});await loadStocks()})}
document.querySelector('#soundBtn').onclick=async()=>{soundReady=true;document.querySelector('#soundBtn').textContent='🔊 SON ACTIF';document.querySelector('#soundBtn').classList.add('on');try{if(Notification.permission==='default')await Notification.requestPermission()}catch{}beep()};
document.querySelector('#closureBtn').onclick=async()=>{if(!settings)return;const enabled=!settings.ordering_enabled;const ok=confirm(enabled?'Réouvrir immédiatement les commandes en ligne ?':'Fermer exceptionnellement les commandes en ligne ?');if(!ok)return;await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify({action:'set_ordering',enabled})});await loadSettings()};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#tab-'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='stocks')await loadStocks();if(b.dataset.tab==='settings')await loadSettings()});
Promise.all([loadSettings(),loadOrders()]);setInterval(loadOrders,3000);setInterval(loadSettings,30000);