const API_BASE=window.PIZZAPLANET_API||'';
let products=[],service=null;
let cart=JSON.parse(localStorage.getItem('pp-cart')||'[]');
let promo=JSON.parse(localStorage.getItem('pp-promo')||'{"reward":"drinks","dough_type":"fine"}');
const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0)/100);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function refreshService(){try{const r=await fetch('/api/service-status',{cache:'no-store'});service=await r.json();const el=document.querySelector('#service');if(service.can_order&&service.payments_configured)el.innerHTML=`<strong class="open">● Commandes ouvertes</strong> · attente estimée <strong>${service.estimated_wait_minutes||15} min</strong> · commandes jusqu'à 22h00`;else if(service.can_order&&!service.payments_configured)el.innerHTML='<strong class="closed">● Paiement en ligne en cours d’activation</strong> · la carte reste consultable';else el.innerHTML=`<strong class="closed">● Commandes fermées</strong> · ${service.exceptional_closed?'fermeture exceptionnelle':'prise de commandes de 17h30 à 22h00'}`;document.querySelector('#checkoutBtn').disabled=!service.can_order||!service.payments_configured}catch{}}
async function load(){const r=await fetch(`${API_BASE}/api/products`,{cache:'no-store'});if(!r.ok)throw new Error('Catalogue indisponible');const d=await r.json();products=d.products||d;normalize();renderProducts();renderCart();await refreshService()}
function normalize(){cart=cart.map(x=>({id:Number(x.id),variant_id:Number(x.variant_id),qty:Math.max(1,Number(x.qty)||1),dough_type:x.dough_type==='epaisse'?'epaisse':'fine'})).filter(x=>Number.isFinite(x.id));save(false)}
function renderProducts(){document.querySelector('#products').innerHTML=products.map(p=>{const vars=p.variants||[];return `<article class="product"><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><div class="selectors"><label>Taille<select data-size="${p.id}">${vars.map(v=>`<option value="${v.id}">${esc(v.label)} — ${money(v.price_cents)}</option>`).join('')}</select></label><label>Pâte<select data-dough="${p.id}"><option value="fine">Fine</option><option value="epaisse">Épaisse</option></select></label></div><button class="btn-main" style="margin-top:10px" data-add="${p.id}" ${p.available===false?'disabled':''}>${p.available===false?'Indisponible':'Ajouter'}</button></article>`}).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.add),v=Number(document.querySelector(`[data-size="${id}"]`).value),d=document.querySelector(`[data-dough="${id}"]`).value;const row=cart.find(x=>x.id===id&&x.variant_id===v&&x.dough_type===d);row?row.qty++:cart.push({id,variant_id:v,dough_type:d,qty:1});save()})}
function detail(i){const p=products.find(x=>Number(x.id)===Number(i.id)),v=p?.variants?.find(x=>Number(x.id)===Number(i.variant_id));return p&&v?{p,v,price:Number(v.price_cents),size:v.size_code}:null}
function stats(){let subtotal=0,m=0,g=0,mediumPrices=[];for(const i of cart){const d=detail(i);if(!d)continue;subtotal+=d.price*i.qty;if(d.size==='moyenne'){m+=i.qty;for(let n=0;n<i.qty;n++)mediumPrices.push(d.price)}if(d.size==='grande')g+=i.qty}const mediumPairs=Math.floor(m/2),largePairs=Math.floor(g/2),pairPrices=mediumPrices.slice().sort((a,b)=>a-b).slice(0,mediumPairs*2),freeCap=mediumPairs?Math.min(1450,...pairPrices):1450;return {subtotal,mediumPairs,largePairs,rewards:mediumPairs+largePairs,freeCap}}
function eligibleFreePizzas(cap=1450){return products.map(p=>{const v=(p.variants||[]).find(x=>x.size_code==='moyenne'&&x.active!==false);return v&&Number(v.price_cents)<=cap&&p.available!==false?{p,v}:null}).filter(Boolean)}
function renderCart(){const root=document.querySelector('#cartItems'),s=stats();root.innerHTML=cart.length?cart.map((i,idx)=>{const d=detail(i);if(!d)return'';return `<div class="cart-row"><span>${esc(d.p.name)} × ${i.qty}<small>${esc(d.v.label)} · pâte ${i.dough_type==='fine'?'fine':'épaisse'}</small></span><span>${money(d.price*i.qty)} <button class="remove" data-rm="${idx}">−</button></span></div>`}).join(''):'<p class="muted">Panier vide.</p>';document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.rm);cart[i].qty--;if(cart[i].qty<=0)cart.splice(i,1);save()});const pr=document.querySelector('#promoChoice');if(s.rewards){const eligible=eligibleFreePizzas(s.freeCap);if(!promo.free_product_id&&eligible[0])promo.free_product_id=eligible[0].p.id;pr.innerHTML=`<div class="promo-choice"><strong>🎁 ${s.rewards} offre(s) disponible(s)</strong><div class="muted">${s.mediumPairs?`${s.mediumPairs} lot(s) de 2 moyennes`:''}${s.mediumPairs&&s.largePairs?' · ':''}${s.largePairs?`${s.largePairs} lot(s) de 2 grandes`:''}</div><label><input type="radio" name="reward" value="drinks" ${promo.reward!=='pizza'?'checked':''}> Boissons offertes (choix sur place)</label><label><input type="radio" name="reward" value="pizza" ${promo.reward==='pizza'?'checked':''}> Pizza moyenne offerte (≤ ${money(s.freeCap)})</label><div id="freePizzaFields" style="${promo.reward==='pizza'?'':'display:none'}"><select id="freePizza">${eligible.map(x=>`<option value="${x.p.id}" ${Number(promo.free_product_id)===Number(x.p.id)?'selected':''}>${esc(x.p.name)} — ${money(x.v.price_cents)}</option>`).join('')}</select><select id="freeDough"><option value="fine" ${promo.dough_type!=='epaisse'?'selected':''}>Pâte fine</option><option value="epaisse" ${promo.dough_type==='epaisse'?'selected':''}>Pâte épaisse</option></select></div></div>`;document.querySelectorAll('input[name="reward"]').forEach(r=>r.onchange=()=>{promo.reward=r.value;persistPromo();renderCart()});document.querySelector('#freePizza')?.addEventListener('change',e=>{promo.free_product_id=Number(e.target.value);persistPromo()});document.querySelector('#freeDough')?.addEventListener('change',e=>{promo.dough_type=e.target.value;persistPromo()})}else pr.innerHTML='';document.querySelector('#cartTotal').textContent=money(s.subtotal);document.querySelector('#miniTotal').textContent=money(s.subtotal);document.querySelector('#cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0);persistPromo()}
function persistPromo(){localStorage.setItem('pp-promo',JSON.stringify(promo))}
function save(render=true){localStorage.setItem('pp-cart',JSON.stringify(cart));if(render)renderCart()}
async function checkout(){if(!cart.length)return alert('Ajoutez au moins une pizza.');if(!service?.can_order)return alert('La prise de commandes est actuellement fermée.');if(!service?.payments_configured)return alert('Le paiement en ligne n’est pas encore activé.');const name=document.querySelector('#customerName').value.trim(),phone=document.querySelector('#customerPhone').value.trim();if(!name)return alert('Indiquez votre nom.');const btn=document.querySelector('#checkoutBtn');btn.disabled=true;btn.textContent='Ouverture du paiement…';try{const items=cart.map(i=>({product_id:i.id,variant_id:i.variant_id,quantity:i.qty,dough_type:i.dough_type}));const r=await fetch('/api/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items,customer:{name,phone},promotion:promo,fulfillment_type:'pickup'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Commande impossible');localStorage.setItem('pp-last-order-id',String(d.order_id));localStorage.setItem('pp-last-order-code',String(d.order_number||''));localStorage.setItem('pp-last-ready-at',String(d.estimated_ready_at||''));location.assign(d.checkout_url)}catch(e){alert(e.message);btn.disabled=false;btn.textContent='Payer et envoyer en cuisine'}}
document.querySelector('#checkoutBtn').onclick=checkout;
document.querySelector('#cartToggle').onclick=()=>{const c=document.querySelector('#cartPanel');c.classList.toggle('collapsed');document.querySelector('#cartToggle').textContent=c.classList.contains('collapsed')?'Voir':'Réduire'};
load().catch(()=>document.querySelector('#products').innerHTML='<p>Catalogue momentanément indisponible.</p>');
setInterval(refreshService,30000);